### ISSUE TITLE
What's the LICENSE ?

### ISSUE THREAD

**Issue by srbhr** [konfig-dev/konfig#790]
Under which LICENSE does konfig falls under?

**Comment by menge101** [comment]
Came here for this as well.

**Comment by dphuang2** [comment]
MIT, thanks for mentioning this!

**Comment by menge101** [comment]
@dphuang2 While I know you said you wanted to release the codebase as-is, a commit to main that contains the license in a license.txt file would be HIGHLY appreciated, or any other gesture that publicly labels the code as being under an MIT license.
